// **************************** type definitions ****************************

###
GET http://localhost:3000/gobbler/definition/list
Authorization: Bearer abc123==

//------------------- vmReboot -------------------
###
POST http://localhost:3000/gobbler/definition/add
Authorization: Bearer abc123==
Content-Type: application/json

{
	"name": "vmReboot",
	"documentation": "virtual machine reboot event",
	"folder": "administration",
	"latencyMinutes": 10,
	"orderedColumns": [
		{"name": "vmId", "type": "string"},
		{"name": "eventTime", "type": "datetime"},
		{"name": "rebootStart", "type": "datetime"},
		{"name": "rebootDuration", "type": "timespan", "optional": true},
        {"name": "rebootReason", "type": "string", "defaultValue": "unknown", "optional": false},
		{"name": "OS", "type": "dynamic", "defaultValue": "{\"os\": \"Windows\", \"version\": \"11\"}", "optional": false}
	]
}

###
GET http://localhost:3000/gobbler/definition/list
Authorization: Bearer abc123==

###
POST http://localhost:3000/gobbler/definition/remove
Authorization: Bearer abc123==
Content-Type: application/json

{ "typeName": "vmReboot" }


//------------------- vmShutdown ------------------- 
###
POST http://localhost:3000/gobbler/definition/add
Authorization: Bearer abc123==
Content-Type: application/json

{
	"name": "vmShutdown",
	"documentation": "virtual machine shutdown event",
	"folder": "administration",
	"latencyMinutes": 10,
	"orderedColumns": [
		{"name": "vmId", "type": "string"},
		{"name": "shutdownStart", "type": "datetime"},
		{"name": "shutdownReason", "type": "string", "defaultValue": "unknown", "optional": false}
	]
}

###
GET http://localhost:3000/gobbler/definition/list
Authorization: Bearer abc123==

###
POST http://localhost:3000/gobbler/definition/remove
Authorization: Bearer abc123==
Content-Type: application/json

{ "typeName": "vmShutdown" }


// ------------------- allscalars -------------------
###
POST http://localhost:3000/gobbler/definition/add
Authorization: Bearer abc123==
Content-Type: application/json

{
	"name": "allscalars",
	"documentation": "table with all scalar types",
	"folder": "folderOne",
	"latencyMinutes": 10,
	"orderedColumns": [
		{"name": "_string", "type": "string", "defaultValue": "value", "optional": true},
        {"name": "_boolean", "type": "bool", "defaultValue": true, "optional": false},
        {"name": "_datetime", "type": "datetime", "defaultValue": "2000-01-01 00:00:01.100", "optional": false},
        {"name": "_dynamic", "type": "dynamic", "defaultValue": "{\"key\": \"value\"}", "optional": false},
        {"name": "_int", "type": "int", "defaultValue": 10, "optional": false},
        {"name": "_real", "type": "real", "defaultValue": 55.55},
        {"name": "_timespan", "type": "timespan", "optional": true}
	]
}


###
GET http://localhost:3000/gobbler/definition/list
Authorization: Bearer abc123==

###
POST http://localhost:3000/gobbler/definition/remove
Authorization: Bearer abc123==
Content-Type: application/json

{ "typeName": "allscalars" }


// **************************** ingestion ****************************

###
POST http://localhost:3000/gobbler/ingest
Authorization: Bearer abc123==
Content-Type: application/json

[
    {"one":"one"},
    {"two":"two"}
]


###
POST http://localhost:3000/gobbler/ingest
Authorization: Bearer abc123==
Content-Type: application/json

[
    { "vmShutdown": { "vmId": "vm_87345882", "shutdownStart": "2018-05-01 01:40:42.902", "shutdownReason": "OS update" } },
    { "vmShutdown": { "vmId": "vm_76445833", "shutdownStart": "2018-05-01 01:40:44.424", "shutdownReason": "Live migration" }}
]

###
POST http://localhost:3000/gobbler/ingest
Authorization: Bearer abc123==
Content-Type: application/json

[
    {"allscalars": {"_string":"Hyundai","_boolean":true,"_datetime":"2018-05-01 01:40:42.902","_dynamic":"{\"color\":\"Crimson\",\"size\":\"small\"}","_int":0,"_real":12537.5948,"_timespan":"7d"}}
]

###
POST http://localhost:3000/gobbler/ingest
Authorization: Bearer abc123==
Content-Type: application/json

[
    {"allscalars":{"_string":"Hyundaiii","_boolean":true,"_datetime":"2018-05-01 01:40:42.902","_dynamic":"{\"color\":\"Crimson\",\"size\":\"small\"}","_int":0,"_real":12537.5948,"_timespan":"7d"}},
    {"allscalars":{"_string":"Plymouth","_boolean":true,"_datetime":"2018-05-01 01:40:43.414","_dynamic":"{\"color\":\"Purple\",\"size\":\"mediem\"}","_int":1,"_real":35280.1204,"_timespan":"8s"}},
    {"allscalars":{"_string":"Mercury","_boolean":true,"_datetime":"2018-05-01 01:40:43.919","_dynamic":"{\"color\":\"Pink\",\"size\":\"ex-large\"}","_int":4,"_real":47188.7112,"_timespan":"9s"}},
    {"allscalars":{"_string":"Subaru","_boolean":false,"_datetime":"2018-05-01 01:40:44.424","_dynamic":"{\"color\":\"Blue\",\"size\":\"large\"}","_int":4,"_real":29606.8954,"_timespan":"3d"}}
]


// ------------------- somescalars -------------------
###
POST http://localhost:3000/gobbler/definition/add
Authorization: Bearer abc123==
Content-Type: application/json

{
    "name": "somescalars",
    "documentation": "table One",
    "folder": "myFolder",
    "latencyMinutes": 10,
    "orderedColumns": [
        { "name": "_string", "type": "string", "defaultValue": "value" },
        { "name": "_boolean", "type": "bool", "defaultValue": true, "optional": true },
        { "name": "_datetime", "type": "datetime", "optional": false },
        { "name": "_int", "type": "int", "optional": false },
        { "name": "_real", "type": "real", "defaultValue": 55.55 }
    ]
}

###
POST http://localhost:3000/gobbler/ingest
Authorization: Bearer abc123==
Content-Type: application/json

[
    { "somescalars": { "_string": "Hyundai", "_boolean": true, "_datetime": "2018-05-01 01:40:42.902", "_int": 0, "_real": 12537.5948 } }
]

###
POST http://localhost:3000/gobbler/ingest
Authorization: Bearer abc123==
Content-Type: application/json

[
    { "somescalars": { "_string": "Hyundaiii", "_boolean": true, "_datetime": "2018-05-01 01:40:42.902", "_int": 0, "_real": 12537.5948 } },
    { "somescalars": { "_string": "Plymouth", "_boolean": true, "_datetime": "2018-05-01 01:40:43.414", "_int": 1, "_real": 35280.1204 } },
    { "somescalars": { "_string": "Mercury", "_boolean": true, "_datetime": "2018-05-01 01:40:43.919", "_int": 4, "_real": 47188.7112 } },
    { "somescalars": { "_string": "Subaru", "_boolean": false, "_datetime": "2018-05-01 01:40:44.424", "_int": 4, "_real": 29606.8954 } }
]
